### 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X))

In [7]:
# 乱序索引
shuffle_indexes

array([121,   0,  58, 139,  57,   9,  66, 128, 111, 122,   4,   5,  20,
        83,   2,  19,  92, 107,  80, 146, 148, 123,  40,  75, 104,  90,
       103, 105, 129,  71,  89, 100, 147,  46,  96, 126, 106, 143,  52,
       138, 124,  47, 140, 141,  78, 120, 125,  51,  76, 142,  23,  94,
        42,  54,  60,  28,  87, 115,  55,  88, 132,  16,  85,  37, 133,
        34, 119, 144,  49,  74,  29,  12,  56,  91,  61,  43,  99, 117,
       108,  79,  11,  31,  14,   7,  53,  65,  35, 118,  30,  69,  72,
        25,  81, 130,  86,  62, 145,  77,  50,  18, 137,  93,  15,  84,
        38,  68,  36, 113, 134,  17,  13, 112,  48,  41,  63,   1,  64,
        97,  10,  27,  59, 135, 102,  73,  82, 101,  26,  33, 136,  70,
        22,   3,  39,  21,  95, 109,   8,  44, 116, 127, 110,  32,   6,
        67, 131, 149,  45,  98, 114,  24])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
X_train.shape

(120, 4)

In [13]:
X_test.shape

(30, 4)

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
X_train.shape

(120, 4)

In [17]:
y_train.shape

(120,)

In [18]:
X_test.shape

(30, 4)

In [19]:
y_test.shape

(30,)

In [20]:
from playML.kNN import KNNClassifier

In [21]:
my_knn_clf = KNNClassifier(3)

In [22]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [23]:
 my_knn_clf

KNN(k=3)

In [24]:
y_predict = my_knn_clf.predict(X_test)

In [25]:
y_predict

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0, 2, 1, 1, 2, 1, 0,
       0, 0, 2, 1, 2, 0, 1, 0])

In [26]:
y_test

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 2, 1, 0,
       0, 0, 2, 1, 2, 0, 1, 0])

In [29]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train test split

In [31]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [35]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)
