### 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X))

In [7]:
# 乱序索引
shuffle_indexes

array([140,  84,  36,  88,  37, 109,  80,  89,  27,  11, 134,  91,  70,
       126, 144, 104,  17, 127,  31,   8, 110,  85,   9,  32, 111,   7,
        95,  25,  20,  93,  51, 122, 115,  48,  55,  90,  33,  46, 139,
        98,  49,  21,  83,  54, 148, 114,  87,  15,  74,  82, 147,  13,
        38,  12,  99,  64, 130, 124,  72,  97, 117,  59, 107, 125,  23,
        92, 136, 105,  24, 116,  69, 118, 106,   4,  10,  62,  58,  22,
        40,  96,  41,  63,  60, 112,  71, 121, 141,  61, 113, 108, 138,
       142, 146, 143, 101,  29, 132,  44,  45,  35,  76,  66,  14, 129,
         2,  79,  65,  77,  16,  78, 128,  43,  52, 120, 123,   5,  26,
       103,   1, 131, 100,  57, 119,  34,  30,  67, 137,  53,  19,  73,
        86,  81, 149,  94, 145,  50,  75,  47, 135, 133,  56,  42,  68,
        39,   3,   0,  28, 102,   6,  18])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
X_train.shape

(120, 4)

In [13]:
X_test.shape

(30, 4)

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
X_train.shape

(120, 4)

In [17]:
y_train.shape

(120,)

In [18]:
X_test.shape

(30, 4)

In [19]:
y_test.shape

(30,)

In [20]:
from playML.kNN import KNNClassifier

In [21]:
my_knn_clf = KNNClassifier(3)

In [22]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [23]:
 my_knn_clf

KNN(k=3)

In [24]:
y_predict = my_knn_clf.predict(X_test)

In [25]:
y_predict

array([0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 2, 1, 1,
       2, 1, 2, 1, 1, 1, 2, 1])

In [26]:
y_test

array([0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 1,
       2, 1, 2, 1, 1, 1, 2, 1])

In [27]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train test split

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)
